version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: emimontanari/mercurio
    container_name: mercurio
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      #NEXT_PUBLIC_APP_URL: 
      AUTH_SECRET: ${AUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}